services:
- type: web
  name: line-chatbot-python-flask
  env: python
  repo: https://github.com/kuochechia/line-chatbot-py.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn SharpLineBot.wsgi:application
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
